/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import { FieldType } from '@boundaryml/baml/native'
import { TypeBuilder as _TypeBuilder, EnumBuilder, EnumViewer, ClassBuilder, ClassViewer } from '@boundaryml/baml/type_builder'
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"

export { FieldType, EnumBuilder, ClassBuilder }

export default class TypeBuilder {
    private tb: _TypeBuilder;
    
    Act: ClassViewer<'Act', "setup" | "incitingIncident" | "plotPoint1" | "confrontation" | "midpoint" | "plotPoint2" | "climax" | "fallingAction" | "resolution" | "duration">;
    
    ActStructure: ClassViewer<'ActStructure', "act1" | "act2" | "act3">;
    
    CharacterArc: ClassViewer<'CharacterArc', "characterName" | "character" | "arcDescription" | "startingState" | "startState" | "endingState" | "endState" | "transformationProcess" | "transformation" | "keyMoments">;
    
    InitialStoryResponse: ClassViewer<'InitialStoryResponse', "storyContent" | "qualityMetrics" | "generationNotes">;
    
    ProjectFieldsResponse: ClassViewer<'ProjectFieldsResponse', "projectTitle" | "shortDescription" | "longDescription">;
    
    QualityAssessment: ClassViewer<'QualityAssessment', "overallScore" | "breakdown">;
    
    QualityBreakdown: ClassViewer<'QualityBreakdown', "clearThreeActProgression" | "strongCharacterArcs" | "compellingStoryBeats" | "effectiveSubplotIntegration" | "cinematicPotential">;
    
    QualityMetric: ClassViewer<'QualityMetric', "score" | "justification">;
    
    QualityMetrics: ClassViewer<'QualityMetrics', "overallQuality" | "structureScore" | "characterDepth" | "coherenceScore" | "conflictTension" | "dialogueQuality" | "genreAlignment" | "audienceEngagement" | "visualStorytelling" | "productionReadiness">;
    
    StoryBeat: ClassViewer<'StoryBeat', "beatId" | "beat" | "timestamp" | "timing" | "description" | "charactersPresent" | "characters" | "emotionalTone">;
    
    StoryStructureResponse: ClassViewer<'StoryStructureResponse', "actStructure" | "threeActStructure" | "storyBeats" | "characterArcs" | "subplots" | "qualityScore" | "qualityAssessment" | "generationNotes">;
    
    StructureValidationResponse: ClassViewer<'StructureValidationResponse', "isReady" | "overallScore" | "strengths" | "weaknesses" | "recommendations" | "criticalIssues">;
    
    Subplot: ClassViewer<'Subplot', "subplotName" | "name" | "description" | "resolution" | "charactersInvolved" | "involvedCharacters">;
    
    

    constructor() {
        this.tb = new _TypeBuilder({
          classes: new Set([
            "Act","ActStructure","CharacterArc","InitialStoryResponse","ProjectFieldsResponse","QualityAssessment","QualityBreakdown","QualityMetric","QualityMetrics","StoryBeat","StoryStructureResponse","StructureValidationResponse","Subplot",
          ]),
          enums: new Set([
            
          ]),
          runtime: DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME
        });
        
        this.Act = this.tb.classViewer("Act", [
          "setup","incitingIncident","plotPoint1","confrontation","midpoint","plotPoint2","climax","fallingAction","resolution","duration",
        ]);
        
        this.ActStructure = this.tb.classViewer("ActStructure", [
          "act1","act2","act3",
        ]);
        
        this.CharacterArc = this.tb.classViewer("CharacterArc", [
          "characterName","character","arcDescription","startingState","startState","endingState","endState","transformationProcess","transformation","keyMoments",
        ]);
        
        this.InitialStoryResponse = this.tb.classViewer("InitialStoryResponse", [
          "storyContent","qualityMetrics","generationNotes",
        ]);
        
        this.ProjectFieldsResponse = this.tb.classViewer("ProjectFieldsResponse", [
          "projectTitle","shortDescription","longDescription",
        ]);
        
        this.QualityAssessment = this.tb.classViewer("QualityAssessment", [
          "overallScore","breakdown",
        ]);
        
        this.QualityBreakdown = this.tb.classViewer("QualityBreakdown", [
          "clearThreeActProgression","strongCharacterArcs","compellingStoryBeats","effectiveSubplotIntegration","cinematicPotential",
        ]);
        
        this.QualityMetric = this.tb.classViewer("QualityMetric", [
          "score","justification",
        ]);
        
        this.QualityMetrics = this.tb.classViewer("QualityMetrics", [
          "overallQuality","structureScore","characterDepth","coherenceScore","conflictTension","dialogueQuality","genreAlignment","audienceEngagement","visualStorytelling","productionReadiness",
        ]);
        
        this.StoryBeat = this.tb.classViewer("StoryBeat", [
          "beatId","beat","timestamp","timing","description","charactersPresent","characters","emotionalTone",
        ]);
        
        this.StoryStructureResponse = this.tb.classViewer("StoryStructureResponse", [
          "actStructure","threeActStructure","storyBeats","characterArcs","subplots","qualityScore","qualityAssessment","generationNotes",
        ]);
        
        this.StructureValidationResponse = this.tb.classViewer("StructureValidationResponse", [
          "isReady","overallScore","strengths","weaknesses","recommendations","criticalIssues",
        ]);
        
        this.Subplot = this.tb.classViewer("Subplot", [
          "subplotName","name","description","resolution","charactersInvolved","involvedCharacters",
        ]);
        
        
    }

    reset(): void {
        this.tb.reset();
        // TODO: This should happen in Rust. Problem is, when we construct the
        // typebuilder we instantiate class builders once and it seems to make
        // a JS copy, bypassing the Rust side? In Python however, every time we
        // access a class builder with @property, we get a new instance that
        // wraps over the Rust type builder, so we only need to call tb.reset().
        // In JS it's not possible unless we refactor the way class builders are
        // accessed.
        
    }

    __tb() {
      return this.tb._tb();
    }

    string(): FieldType {
        return this.tb.string()
    }

    literalString(value: string): FieldType {
        return this.tb.literalString(value)
    }

    literalInt(value: number): FieldType {
        return this.tb.literalInt(value)
    }

    literalBool(value: boolean): FieldType {
        return this.tb.literalBool(value)
    }

    int(): FieldType {
        return this.tb.int()
    }

    float(): FieldType {
        return this.tb.float()
    }

    bool(): FieldType {
        return this.tb.bool()
    }

    list(type: FieldType): FieldType {
        return this.tb.list(type)
    }

    null(): FieldType {
        return this.tb.null()
    }

    map(key: FieldType, value: FieldType): FieldType {
        return this.tb.map(key, value)
    }

    union(types: FieldType[]): FieldType {
        return this.tb.union(types)
    }

    addClass<Name extends string>(name: Name): ClassBuilder<Name> {
        return this.tb.addClass(name);
    }

    addEnum<Name extends string>(name: Name): EnumBuilder<Name> {
        return this.tb.addEnum(name);
    }

    addBaml(baml: string): void {
        this.tb.addBaml(baml);
    }
}